# Week 04: Pandas DataFrame 

**Course:** MATH7810 Python for Data Science (AY2026/27)

The name "pandas" comes from **panel data** (observations over time for the same units). In this course we use it as a table toolkit: rows = observations, columns = variables.

**Class path:** Series (values + index) → DataFrame create & components → one useful subset → `head` / `info` / `describe` / `isna` / `groupby`.

**Recap from Week 3 (dict → DataFrame):** In `W03_Ch2_PythonDataStructures.ipynb` you built a **dict of equal-length lists** (each key = a column name). That is how we often create a DataFrame: `pd.DataFrame(that_dict)`. A Series is the other dict idea — key → value becomes index → data.

**Pandas and NumPy:** NumPy gives fast numeric **arrays** and vectorized math. Pandas builds on that for **labeled tables**: a Series stores values in a NumPy-like array plus an index; a DataFrame is columns of Series sharing one index. So things like `.values`, `mean`, `std`, and doing math on a whole column work much like NumPy — but Pandas also keeps row/column names, and different columns can have different types.

## Learning goals
1. See a **Series** as values + an **index**
2. Build a **DataFrame** from a dict of lists and name its three components
3. **Subset** rows (boolean filter) and columns (by name)
4. Run a first **exploration & summary** pass: `head`, `info`, `describe`, `isna()`, `groupby`

In [1]:
# Purpose: load pandas and NumPy

import pandas as pd
import numpy as np

## 1. Series
A **Series** is a 1D array of data plus an **index** (labels). Think: one column of a spreadsheet with **row** labels.

In [2]:
# Purpose: create a Series and inspect values + index

s = pd.Series([4, 7, -5, 3])
print(s)
print(s.values)   # the data (NumPy-like)
print(s.index)    # the labels (default: 0, 1, 2, ...)

0    4
1    7
2   -5
3    3
dtype: int64
[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)

In [3]:
# Purpose: Series with custom index; change one value by label

s2 = pd.Series([4, 707, -52, 30000], index=['a', 'bb', 'ccc', 'dddd'])
print(s2)
s2['a'] = 7
s2

a           4
bb        707
ccc       -52
dddd    30000
dtype: int64

a           7
bb        707
ccc       -52
dddd    30000
dtype: int64

## 2. DataFrame
A **DataFrame** is a table: each column is a Series sharing the same index. Columns can have different types.

In [4]:
# Purpose: build a DataFrame from a dict of equal-length lists

d = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada',
              'Texas', 'Texas', 'Texas', 'Oregon', 'Oregon', 'Utah', 'Utah'],
    'year':  [2000, 2001, 2002, 2000, 2001, 2002,
              2000, 2001, 2002, 2001, 2002, 2001, 2002],
    'pop':   [1.5, 1.7, 3.6, 2.6, 2.4, 2.9,
              7.2, 7.1, 7, 3.5, 3.7, 2.2, 2.6]
}
f = pd.DataFrame(d)
f

     state  year  pop
0     Ohio  2000  1.5
1     Ohio  2001  1.7
2     Ohio  2002  3.6
3   Nevada  2000  2.6
4   Nevada  2001  2.4
5   Nevada  2002  2.9
6    Texas  2000  7.2
7    Texas  2001  7.1
8    Texas  2002  7.0
9   Oregon  2001  3.5
10  Oregon  2002  3.7
11    Utah  2001  2.2
12    Utah  2002  2.6

In [5]:
# Purpose: three components of a DataFrame

print(f.values)    # 1. data (2D)
print(f.index)     # 2. row index
print(f.columns)   # 3. column names

[['Ohio' 2000 1.5]
 ['Ohio' 2001 1.7]
 ['Ohio' 2002 3.6]
 ['Nevada' 2000 2.6]
 ['Nevada' 2001 2.4]
 ['Nevada' 2002 2.9]
 ['Texas' 2000 7.2]
 ['Texas' 2001 7.1]
 ['Texas' 2002 7.0]
 ['Oregon' 2001 3.5]
 ['Oregon' 2002 3.7]
 ['Utah' 2001 2.2]
 ['Utah' 2002 2.6]]
RangeIndex(start=0, stop=13, step=1)
Index(['state', 'year', 'pop'], dtype='str')

With no custom row labels, Pandas uses a **`RangeIndex`**: `start=0, stop=13, step=1` means the row labels are **0 through 12** (13 rows; `stop` is exclusive, like `range` in Python). It prints the rule, not the full list `0, 1, …, 12`.

## 3. One useful subset
Filter **rows** with a condition; select **columns** by name.

In [6]:
# Purpose: subset rows (boolean filter) and columns (by name)

# rows where population > 3
print(f[f['pop'] > 3])
# f['pop'] > 3 makes True/False for each row; f[...] keeps only the True rows

# two columns only
f[['state', 'pop']].head()

     state  year  pop
2     Ohio  2002  3.6
6    Texas  2000  7.2
7    Texas  2001  7.1
8    Texas  2002  7.0
9   Oregon  2001  3.5
10  Oregon  2002  3.7

    state  pop
0    Ohio  1.5
1    Ohio  1.7
2    Ohio  3.6
3  Nevada  2.6
4  Nevada  2.4

In [7]:
# Purpose: sort rows by a column (optional in class if time is tight)

f.sort_values('pop', ascending=False).head()

     state  year  pop
6    Texas  2000  7.2
7    Texas  2001  7.1
8    Texas  2002  7.0
10  Oregon  2002  3.7
2     Ohio  2002  3.6

## 4. Exploration & summary
Use these steps on any rectangular dataset in your Codespace.

In [8]:
# Purpose: tiny demo table (replace with pd.read_csv('your_file.csv') when you have a CSV)

df = pd.DataFrame({
    'time_on_page': [30, 45, 20, np.nan, 50, 80, 35, 90, 40, 70],
    'order_value': [25, 40, 18, np.nan, 48, 70, 30, 85, 35, 60],
    'checkout_page': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B']
})
# use np.nan (or None / pd.NA) for missing — the string 'na' is NOT treated as missing
df.head()

   time_on_page  order_value checkout_page
0          30.0         25.0             A
1          45.0         40.0             B
2          20.0         18.0             A
3           NaN          NaN             B
4          50.0         48.0             A

In [9]:
# Purpose: shape, types, and numeric/categorical summaries

print(df.shape)
df.info()

# numeric columns only
print(df[['time_on_page', 'order_value']].describe())

# frequency table for the categorical column
df['checkout_page'].value_counts()

(10, 3)
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   time_on_page   9 non-null      float64
 1   order_value    9 non-null      float64
 2   checkout_page  10 non-null     str
dtypes: float64(2), str(1)
memory usage: 372.0 bytes
       time_on_page  order_value
count      9.000000     9.000000
mean      51.111111    45.666667
std       23.819343    22.175437
min       20.000000    18.000000
25%       35.000000    30.000000
50%       45.000000    40.000000
75%       70.000000    60.000000
max       90.000000    85.000000

checkout_page
A    5
B    5
Name: count, dtype: int64

`df.shape` → `(10, 3)` means **10 rows** and **3 columns**.

`df.info()` is a short report: how many rows (`RangeIndex: 10 entries`), each column’s name, how many non-missing values (`10 non-null`), and the type (`int64` = whole numbers; `object` = text/labels here, e.g. `'A'`/`'B'`).

Use `describe()` on **numeric** columns; for a category like `checkout_page`, use `value_counts()` (a frequency table).

In [10]:
# Purpose: missingness and how many distinct values per column

print(df.isna().sum())
print(df.nunique())

time_on_page     1
order_value      1
checkout_page    0
dtype: int64
time_on_page     9
order_value      9
checkout_page    2
dtype: int64

In [11]:
# Purpose: group summary (count / mean / SD by checkout page)

# 1. groupby('checkout_page') — split rows into groups A and B
# 2. ['order_value'] — look only at that column within each group
# 3. .agg([...]) — compute count, mean, and std for each group

df.groupby('checkout_page')['order_value'].agg(['count', 'mean', 'std'])

               count   mean        std
checkout_page
A                  5  31.20  11.300442
B                  4  63.75  18.874586